### ISSUE TITLE
能否记录一下【转换列表文件】

### ISSUE THREAD

**Issue by cgsgood** [xresloader/xresconv-gui#22]
能否记录一下【转换列表文件】，不用每次打开都需要选择【转换列表文件】，让使用起来更加方便？

**Comment by owent** [comment]
可以启动选项里加 `--input <文件名>` 来启动后默认打开清单文件的。建一个快捷方式然后加这个路径，我们自己这边是这么给策划用的。

**Comment by cgsgood** [comment]
> 可以启动选项里加 `--input <文件名>` 来启动后默认打开清单文件的。建一个快捷方式然后加这个路径，我们自己这边是这么给策划用的。

感谢，非常好的方法！
